# https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema?view=vsts

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: "Release"
  Project: "$(Build.SourcesDirectory)/src/EasyConfig.SiteExtension/EasyConfig.SiteExtension.csproj"
  ProjectFolder: "$(Build.SourcesDirectory)/src/EasyConfig.SiteExtension"
  NugetFolder: "$(Build.SourcesDirectory)/src/EasyConfig.SiteExtension.NuGet"
  GitVersion: "5.1.2"

name: $(Year:yy)$(DayOfYear)$(Rev:rr)

steps:
  - task: UseDotNet@2
    displayName: Use .NET Core $(DotNetVersion)
    inputs:
      packageType: "sdk"
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: 'Install GitVersion: $(GitVersion)'
    inputs:
      command: custom
      custom: 'tool'
      arguments: 'install GitVersion.Tool --version $(GitVersion)  --tool-path ./pipelines/tools/gitversion'

  - task: PowerShell@2
    displayName: Run GitVersion
    inputs:
      targetType: "filePath"
      filePath: "pipelines/tools/Run-GitVersion.ps1"
      workingDirectory: "$(ProjectFolder)"

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: "restore"
      projects: "$(Project)"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: "build"
      projects: "$(Project)"
      arguments: "--configuration $(buildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: "publish"
      projects: "$(Project)"
      arguments: "--configuration $(buildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: Pack Internal
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: "pack"
      packagesToPack: "$(Project)"
      nobuild: true
      arguments: "--configuration $(buildConfiguration)"
      buildProperties: "VersionPrefix=$(GitVersion.MajorMinorPatch);VersionSuffix=pre-$(Build.BuildNumber)"
      packDirectory: "$(Build.ArtifactStagingDirectory)"
      verbosityPack: Normal

  - task: DotNetCoreCLI@2
    displayName: Pack Release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: "pack"
      packagesToPack: "$(Project)"
      nobuild: true
      arguments: "--configuration $(buildConfiguration)"
      buildProperties: "VersionPrefix=$(GitVersion.MajorMinorPatch);VersionSuffix="
      packDirectory: "$(Build.ArtifactStagingDirectory)"
      verbosityPack: Normal

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: NuGet
      parallel: true